os:
  - linux

dist: trusty

sudo: false

language: cpp

compiler:
  - gcc-8

addons:
  apt:
    update: true

    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc-8
      - g++-8
      - valgrind

script:
  - g++-8 -o travis_gcc_cpp17 Catch2.cpp Components/*.cpp Filter/*.cpp -std=c++14 -Wall -g -Wextra -Wshadow -Wnon-virtual-dtor -pedantic
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all ./travis_gcc_cpp17
