language: cpp

compiler:
  - gcc

addons:
  apt:
    update: true

    packages:
      - gcc-6
      - valgrind

script:
  - g++ -o travis_gcc_cpp17 Catch2.cpp Components/*.cpp Filter/*.cpp -std=c++1y
  - valgrind --leak-check=yes ./travis_gcc_cpp17
